### ISSUE TITLE
TypeError: denoise_wavelet() got an unexpected keyword argument 'method'

### ISSUE THREAD

**Issue by ripsm** [iamaaditya/pixel-deflection#3]
Hello, I get the following error in after defense:

After Defense :
Traceback (most recent call last):
  File "main.py", line 90, in <module>
    image = process_image(args, args.image, defend=True)
  File "main.py", line 48, in process_image
    return denoiser(args.denoiser, img/255.0, args.sigma)*255.0
  File "/home/rips/...../pixel-deflection/methods.py", line 16, in denoiser
    return denoise_wavelet(img,sigma=sigma, mode='soft', multichannel=True,convert2ycbcr=True, method='BayesShrink')
TypeError: denoise_wavelet() got an unexpected keyword argument 'method'

**Comment by iamaaditya** [comment]
You need Scipy 1.0+ (older versions did not have method parameter, and also did not have BayesShrink as shrinkage parameter). If you want to continue using existing Scipy, you can change the line like this:

`return denoise_wavelet(img,sigma=sigma, mode='soft', multichannel=True,convert2ycbcr=True)`
